const MOUTH_OPEN = {
  closed: 0,
  narrow: 0.32,
  open: 0.68,
  wide: 1,
};

const VISEMES = {
  closed: {
    jaw: 0.03,
    jawMorph: 0.03,
    wideMorph: 0.02,
    funnel: 0.04,
    lift: 0.02,
    cavityX: 0.88,
    cavityY: 0.16,
    cavityZ: 1,
    teeth: false,
    viseme_sil: 1,
    viseme_PP: 0.12,
    viseme_FF: 0,
    viseme_aa: 0,
    viseme_E: 0,
    viseme_I: 0,
    viseme_O: 0,
    viseme_U: 0,
    jawOpen: 0.02,
    mouthFunnel: 0.04,
    mouthSmileLeft: 0.06,
    mouthSmileRight: 0.06,
    browInnerUp: 0.05,
  },
  narrow: {
    jaw: 0.11,
    jawMorph: 0.28,
    wideMorph: 0.1,
    funnel: 0.82,
    lift: 0.22,
    cavityX: 0.72,
    cavityY: 0.62,
    cavityZ: 1.06,
    teeth: true,
    viseme_sil: 0,
    viseme_PP: 0,
    viseme_FF: 0.14,
    viseme_aa: 0.08,
    viseme_E: 0,
    viseme_I: 0,
    viseme_O: 0.22,
    viseme_U: 0.84,
    jawOpen: 0.14,
    mouthFunnel: 0.52,
    mouthSmileLeft: 0,
    mouthSmileRight: 0,
    browInnerUp: 0.08,
  },
  open: {
    jaw: 0.2,
    jawMorph: 0.66,
    wideMorph: 0.32,
    funnel: 0.16,
    lift: 0.52,
    cavityX: 1.18,
    cavityY: 1.08,
    cavityZ: 1,
    teeth: true,
    viseme_sil: 0,
    viseme_PP: 0,
    viseme_FF: 0,
    viseme_aa: 0.92,
    viseme_E: 0.14,
    viseme_I: 0,
    viseme_O: 0.16,
    viseme_U: 0,
    jawOpen: 0.4,
    mouthFunnel: 0.08,
    mouthSmileLeft: 0.1,
    mouthSmileRight: 0.1,
    browInnerUp: 0.12,
  },
  wide: {
    jaw: 0.3,
    jawMorph: 0.94,
    wideMorph: 0.92,
    funnel: 0.06,
    lift: 0.4,
    cavityX: 1.46,
    cavityY: 1.34,
    cavityZ: 1,
    teeth: true,
    viseme_sil: 0,
    viseme_PP: 0,
    viseme_FF: 0,
    viseme_aa: 0.22,
    viseme_E: 0.42,
    viseme_I: 0.74,
    viseme_O: 0,
    viseme_U: 0,
    jawOpen: 0.3,
    mouthFunnel: 0.04,
    mouthSmileLeft: 0.36,
    mouthSmileRight: 0.36,
    browInnerUp: 0.16,
  },
};

export function mouthOpenFromLip(lip) {
  return MOUTH_OPEN[lip] ?? 0;
}

export function visemeFromLip(lip) {
  return VISEMES[lip] ?? VISEMES.closed;
}

export function rigPoseFromScene(scene) {
  const lip = scene.lip;
  return {
    lip,
    gesture: scene.gesture ?? "idle",
    talking: scene.pose === "talk",
    viseme: visemeFromLip(lip),
    mouthOpen: mouthOpenFromLip(lip),
    headPitch: (scene.tilt ?? 0) + (scene.nod ?? 0),
    glassesDrop: scene.glasses ?? 0,
    breathe: scene.idleBreathe ?? 0,
    bounce: scene.bounce ?? 0,
  };
}
